name: SonarCloud Verification Service

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    uses: zenwk-org/zenwk-workflows/.github/workflows/sonarcloud.yml@main
    with:
      projectKey: ZenWkZen_zenwk-verification
      organization: zenwk-org
      microserviceDir: zenwk-verification  # Ruta relativa al repo ra√≠z
    secrets: inherit